### ISSUE TITLE
Улучшения PBox

### ISSUE THREAD

**Issue by SladeThe** [MikeMirzayanov/pbox#4]
1. Расширить логирование действий PBox. Например, сейчас сложно понять, что он делает: выполняет чистую установку, обновляет (с какой версии?) или что-то ещё.
2. Сделать расширенный мануал. Сейчас в usage указаны только команды install/uninstall.
3. Maven 3 везде оперирует переменной окружения M2_HOME (возможно, M3_HOME тоже используется). Если привязать M2_HOME к Maven 3, то очевидно это войдёт в конфликт с пакетом Maven 2. Вероятно, стоит добавить настройку взаимоисключений пакета (если установлен один, то второй не поставится). Она будет также полезна, например, для пакетов K-Lite Codec Pack Full и Mega, которые ставятся (по умолчанию) в один и тот же каталог.

**Comment by MikeMirzayanov** [comment]
Если произошло автообновление пакета, то писать подробнее вместо Package 'tools$1.2' installed to the 'C:\Programs\tools'.
